#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct DrawArraysIndirectCommand {
    uint count;
    uint primCount;
    uint first;
    uint baseInstance;
};

layout(std430, binding = 0) readonly buffer TriangleCounter {
    uint TriangleCount;
};

layout(std430, binding = 1) buffer DrawCommand {
    DrawArraysIndirectCommand Command;
};

uniform int maxTriangles;

void main() {
    uint triangleCount = min(TriangleCount, uint(maxTriangles));
    Command.count = triangleCount * 3u;
    Command.primCount = 1u;
    Command.first = 0u;
    Command.baseInstance = 0u;
}
