#version 430

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

struct Entry {
    uint originalIndex;
    uint hash;
    uint key;
    uint padding;
};

layout(std430, binding = 0) buffer EntriesBuffer {
    Entry Entries[];
};

uniform int numEntries;
uniform int groupWidth;
uniform int groupHeight;
uniform int stepIndex;

void main() {
    uint i = gl_GlobalInvocationID.x;

    uint width = uint(groupWidth);
    uint height = uint(groupHeight);
    uint step = uint(stepIndex);

    uint hIndex = i & (width - 1u);
    uint indexLeft = hIndex + (height + 1u) * (i / width);
    uint rightStepSize = step == 0u ? height - 2u * hIndex : (height + 1u) / 2u;
    uint indexRight = indexLeft + rightStepSize;

    if (indexRight >= uint(numEntries)) {
        return;
    }

    uint valueLeft = Entries[indexLeft].key;
    uint valueRight = Entries[indexRight].key;

    if (valueLeft > valueRight) {
        Entry temp = Entries[indexLeft];
        Entries[indexLeft] = Entries[indexRight];
        Entries[indexRight] = temp;
    }
}
