#version 430

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

struct Entry {
    uint originalIndex;
    uint hash;
    uint key;
    uint padding;
};

layout(std430, binding = 0) readonly buffer EntriesBuffer {
    Entry Entries[];
};

layout(std430, binding = 1) buffer OffsetsBuffer {
    uint Offsets[];
};

uniform int numEntries;

void main() {
    uint i = gl_GlobalInvocationID.x;

    if (i >= uint(numEntries)) {
        return;
    }

    uint nullValue = uint(numEntries);
    uint key = Entries[i].key;
    uint keyPrev = i == 0u ? nullValue : Entries[i - 1u].key;

    if (key != keyPrev) {
        Offsets[key] = i;
    }
}
